Troca de ícones e adicao da pagina de template (--ainda nao esta funcionando)
leticia-pontes/eng-software-termooo pull request #19
Opened 2024-05-29 00:15 UTC by IsaEstellaa

2024-05-29 02:18 UTC, giovanaoliveira-14 requested changes
Isa, as alterações estão de boas, porém, esse PR esta indo para a master e deve ir para a develop

2024-05-29 02:20 UTC, giovanaoliveira-14 commented
Se caso tiver mais alterações, pode estar fazendo, porém, troque a branch master pela branch develop

2024-05-30 04:57 UTC, leticia-pontes approved these changes

2024-05-30 04:58 UTC, leticia-pontes commented
eu aprovei o review porque eu tinha falado para subir na master ao invés da develop, mas ainda não fiz o merge.

2024-05-30 17:35 UTC, giovanaoliveira-14 approved these changes

2024-05-30 17:36 UTC, merged